/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TextSegment = IDL.Record({
  'soundEffect' : IDL.Text,
  'content' : IDL.Text,
  'startTimeMs' : IDL.Nat,
  'transitionEffect' : IDL.Text,
  'styleOverrides' : IDL.Text,
  'animationPreset' : IDL.Text,
  'durationMs' : IDL.Nat,
});
export const StyleSettings = IDL.Record({
  'backgroundColor' : IDL.Text,
  'shadow' : IDL.Bool,
  'fontFamily' : IDL.Text,
  'fontSize' : IDL.Nat,
  'outline' : IDL.Bool,
  'textColor' : IDL.Text,
});
export const Time = IDL.Int;
export const AnimationProject = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : Time,
  'textSegments' : IDL.Vec(TextSegment),
  'styleSettings' : StyleSettings,
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Vec(TextSegment), StyleSettings],
      [],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getProject' : IDL.Func([IDL.Text], [AnimationProject], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(AnimationProject)], ['query']),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Vec(TextSegment), StyleSettings],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TextSegment = IDL.Record({
    'soundEffect' : IDL.Text,
    'content' : IDL.Text,
    'startTimeMs' : IDL.Nat,
    'transitionEffect' : IDL.Text,
    'styleOverrides' : IDL.Text,
    'animationPreset' : IDL.Text,
    'durationMs' : IDL.Nat,
  });
  const StyleSettings = IDL.Record({
    'backgroundColor' : IDL.Text,
    'shadow' : IDL.Bool,
    'fontFamily' : IDL.Text,
    'fontSize' : IDL.Nat,
    'outline' : IDL.Bool,
    'textColor' : IDL.Text,
  });
  const Time = IDL.Int;
  const AnimationProject = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : Time,
    'textSegments' : IDL.Vec(TextSegment),
    'styleSettings' : StyleSettings,
  });
  
  return IDL.Service({
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Vec(TextSegment), StyleSettings],
        [],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getProject' : IDL.Func([IDL.Text], [AnimationProject], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(AnimationProject)], ['query']),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Vec(TextSegment), StyleSettings],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };