/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimationProject {
  'title' : string,
  'createdAt' : Time,
  'textSegments' : Array<TextSegment>,
  'styleSettings' : StyleSettings,
}
export interface StyleSettings {
  'backgroundColor' : string,
  'shadow' : boolean,
  'fontFamily' : string,
  'fontSize' : bigint,
  'outline' : boolean,
  'textColor' : string,
}
export interface TextSegment {
  'soundEffect' : string,
  'content' : string,
  'startTimeMs' : bigint,
  'transitionEffect' : string,
  'styleOverrides' : string,
  'animationPreset' : string,
  'durationMs' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'createProject' : ActorMethod<
    [string, Array<TextSegment>, StyleSettings],
    undefined
  >,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getProject' : ActorMethod<[string], AnimationProject>,
  'listProjects' : ActorMethod<[], Array<AnimationProject>>,
  'updateProject' : ActorMethod<
    [string, Array<TextSegment>, StyleSettings],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];